<a href="https://colab.research.google.com/github/Pavanimale36/datascience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
#1d array
l = [1,2,3,4,5]
print(l)
print("type of list",type(l))
#after converting into list
l = np.array(l)
print(l)
print("type of array",type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
type of list <class 'list'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [ ]:
#creating 2d arrays
l1=[1,2,3,4,5]
l2=[3,4,5,6,7]
l3=[5,6,7,8,9]
l4=np.array([
    l1,
    l2,
    l3
])
print(l4)
print(l4.ndim)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]
2


In [ ]:
l1=[
 [1,2],
 [3,4]
]
l2=[
 [1,2],
 [3,4]
]
l3=np.array([
    l1,l2
])
print(l3)
print(l3.ndim)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3


In [ ]:
# different ways to create arrays in numpy

In [ ]:
l=[1,2,3,4,5]
p=(1,2,3,4,5)
l=np.array(l)
p=np.array(p)
print("list converted into array")
print(l)
print("tuple converted into array")
print(p)

list converted into array
[1 2 3 4 5]
tuple converted into array
[1 2 3 4 5]


In [ ]:
#fromiter
l=[1,2,3,4,5]
arr=np.fromiter(l,dtype=int)
print(arr)

[1 2 3 4 5]


In [ ]:
#arange
l=np.arange(5)
print(l)
l=np.arange(1,9)
print(l)
l=np.arange(1,10,2)
print(l)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [ ]:
arr=np.linspace(1,5,8)
print(arr)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [ ]:
arr=np.empty((5,3))
print(arr)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


In [ ]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
2


In [ ]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
2
int64


In [ ]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[1 2 3 4 5]
 [4 5 6 7 8]]
[ 5  7  9 11 13]
[15 30]


In [ ]:
#indexing
l=[10,20,30,40]
arr=np.array(l)
print(arr[3])
print(arr[0])
print(arr[1])
print(arr[-1])

40
10
20
40


In [ ]:
l2=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[1,0])
print(l2[0])
print(l2[1])
print(l2[2])
print(l2[:,0])
print(l2[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
4
[1 2 3]
[4 5 6]
[7 8 9]
[1 4 7]
[2 5 8]


In [ ]:
#l[start:end:step]
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
print(arr[0:2])
print(arr[0:5])
print(arr[1:5])
print(arr[0:5:2])
print(arr[1:])
print(arr[:4])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[2 3 4 5]
[1 3 5]
[2 3 4 5]
[1 2 3 4]


In [18]:
#l[row_start:row_end,col_start:col_end]
l=np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11]
])
print(l)
print(l[0:2,0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]]


In [19]:
import numpy as np

In [20]:
arr1= np.array([1,2,3])
arr2= np.array([10,20,30])
print(arr1+arr2)
#subtration
#10-1=9
#20-2=18
#30-3=27
print(arr2-arr1)
#multiplication
#10*1=10
#20*2=20
#30*1=30
print(arr1*arr2)
# #division
#10/1=10
#20/2=10
#30/3=10
print(arr2/arr1)
print(arr2//arr1)
print(arr2%arr1)
print(arr1**2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[10 10 10]
[0 0 0]
[1 4 9]


In [21]:
#aggregate function:functions used to summarize data

In [22]:
l=np.array([10,20,20,40,50,60])
#add all elements=sum
print(np.sum(l))
#average
print(np.mean(l))
#minimum
print(np.min(l))
#maximum value
print(np.max(l))
#standard devation
print(np.std(l))
#variance
print(np.var(l))
#size of element in an array
print(np.size(l))
#argmax:gives the index position of the largest value
print(np.argmax(l))
#argmin #it gives the index position of the minimum value
print(np.argmin(l))
#applying square root
print(np.sqrt(l))

200
33.333333333333336
10
60
17.950549357115012
322.22222222222223
6
5
0
[3.16227766 4.47213595 4.47213595 6.32455532 7.07106781 7.74596669]


In [23]:
arr=np.array([-1,-2,-3,-4,-5])
print(np.abs(arr)) #absolute function converts negative to positive

[1 2 3 4 5]


In [24]:
#numpy rounding functions
arr=np.array([1.2,2.7,3.5,4.1,5.9])
#round:round values to nearest integer
# 1.2->1
# 2.7->3
# 3.5->3
# 4.1->4
#5.9->6
print(np.round(arr))

[1. 3. 4. 4. 6.]


In [25]:
arr=np.array([1.2,2.7,3.5,4.1,5.9])
#floor it will always gives lower integer values
#1.2->1
#2.7->2
#3.5->3
#4.1->4
#5.9->5
print(np.floor(arr))

[1. 2. 3. 4. 5.]
